project:
  type: website

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  repo-url: "https://github.com/chen-001/factor_reader"
  navbar:
    background: primary
    search: true
  sidebar:
    style: "docked"

metadata-files: [nbdev.yml, sidebar.yml]