# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/factor_reader',
                'doc_host': 'https://chen-001.github.io',
                'git_url': 'https://github.com/chen-001/factor_reader',
                'lib_path': 'factor_reader'},
  'syms': {'factor_reader.core': {'factor_reader.core.foo': ('core.html#foo', 'factor_reader/core.py')}}}
